const mongoose = require("mongoose");

const ratesSchema = {
    forCarrier: String,
    currency: String,
    contact: String,
    revisedDate: Date,
    expired: Boolean,
    origin: String,
    originZone: String,
    dest: String,
    destZone: String,
    transitAirport: String,
    transitCarrier: String,
    fromDate: Date,
    untilDate: Date,
    rateCode: String,
    kgLb: String,
    sellBuy: String,
    prepaidCollect: String,
    salesRegion: String,
    dealCode: String,
    reference: String,
    priceClass: String,
    serviceLevel: String,
    flightGroup: String,
    uldType: String,
    shcAddon: String,
    priceTemplate: String,
    allotPrice: String,
    weekday: String,
    premium: Boolean,
    shipper: String,
    agent: String,
    remarksInt: String,
    remarksExt: String,
    minAmount: Number,
    n: Number,
    q45: Number,
    q100: Number,
    q300: Number,
    q500: Number,
    q1000: Number,
    q3000: Number,
    allIn: Boolean
};

const Rate = mongoose.model("Rate", ratesSchema);

module.exports = Rate;